HieuAddGameOverUI
TDVien05/F_Type pull request #3
Opened 2024-11-27 16:29 UTC by NgoHieu-coder

2024-11-27 23:56 UTC, QuangWorkIT commented
1. Solve conflict
2. Đổi lại background
3. Dùng hàm changeScene của Viên đổi tên biến ko cần mỗi scene 1 hàm

2024-11-28 00:39 UTC, AnataAria requested changes

2024-11-28 00:39 UTC, AnataAria commented on Assets/BG_Galaxy.jpg
Use the original image provide file by @QuangWorkIT , if you have other reason why u use this, please comment here and btw make a folder name Sprites and put all assets like image to it , don't put it to root folder, that will made a mess

2024-11-28 00:39 UTC, AnataAria commented on Assets/BG_Galaxy.jpg.meta
Same as above

2024-11-28 00:39 UTC, AnataAria commented on Assets/GOAsset.meta
Save as above

2024-11-28 00:39 UTC, AnataAria commented on Assets/Script/Scene_Script/changeScene.cs
File name and class name wrong syntax, should use camel case, not this, and use code of @TDVien05 , contact him for more detail

2024-11-28 00:39 UTC, AnataAria commented on Assets/Script/Scene_Script/changeScene.cs
And Folder Scene_Scripts should not name like this, that will more unreasonable bugs in future and hard to read, remove underline

2024-11-28 00:39 UTC, AnataAria commented on Assets/Script/Scene_Script/changeScene.cs
>      }
I dont think that will Ok, wrong name convention

2024-11-28 04:11 UTC, QuangWorkIT commented on Assets/BG_Galaxy.jpg
Change the background according to the UI folder

2024-11-28 15:45 UTC, closed without merging